name: siskang
version: 1.0.0+1
publish_to: none
description: Sistem Informasi Kemajuan Akademik Pascasarjana Undiksha.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  introduction_screen: 3.0.0
  firebase_core: 1.13.1
  lottie: 1.2.2
  firebase_auth: 3.3.11
  package_info_plus: 1.4.0
  flutter_secure_storage: 5.0.2
  flutter_custom_clippers: 2.0.0
  settings_ui: 2.0.2
  avatar_glow: 2.0.2
  url_launcher: 6.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/images/
    - assets/fonts/
  fonts: 
    - family: Muli
      fonts: 
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
        - asset: assets/fonts/muli/Muli Light.ttf
  uses-material-design: true

